apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespaces: readme-editor
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 60 1000
    appendonly yes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: readme-editor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: readme-editor
spec:
  replicas: 1
  strategy:
    type: Recreate          
  template:
    metadata:
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-config
          configMap:
            name: redis-config

--- 
kind: service
metadata:
  name: redis
  namespace: readme-editor
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis